@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.bluebeaker.justextradrags.network;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;