@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.bluebeaker.justextradrags.client;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;