@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.bluebeaker.justextradrags.config;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;