@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.bluebeaker.justextradrags.compat;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;